"""update model 

Revision ID: 6e00f0cf83d5
Revises: 1dc9f925c6c6
Create Date: 2026-02-05 10:31:23.824676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6e00f0cf83d5'
down_revision: Union[str, Sequence[str], None] = '1dc9f925c6c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cases', 'expected_status',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True,
               existing_comment='预期响应状态码')
    op.alter_column('cases', 'expected_response_time',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_comment='预期响应时间（ms）')
    op.alter_column('tasks', 'host',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False,
               existing_comment='压测目标地址，如http://127.0.0.1:8001')
    op.alter_column('tasks', 'runtime_seconds',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_comment='运行了时长（秒）')
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=50),
               comment='用户名，用于登录',
               existing_nullable=False)
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(length=255),
               comment='用户密码',
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=100),
               comment='邮箱',
               existing_nullable=True)
    op.alter_column('users', 'phone',
               existing_type=mysql.VARCHAR(length=100),
               comment='手机号',
               existing_nullable=True)
    op.alter_column('users', 'avatar',
               existing_type=mysql.VARCHAR(length=100),
               comment='头像',
               existing_nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               comment='用户状态',
               existing_nullable=False)
    op.alter_column('users', 'is_admin',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否超管',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_admin',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='是否超管',
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='用户状态',
               existing_nullable=False)
    op.alter_column('users', 'avatar',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='头像',
               existing_nullable=True)
    op.alter_column('users', 'phone',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='手机号',
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='邮箱',
               existing_nullable=True)
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='用户密码',
               existing_nullable=False)
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='用户名，用于登录',
               existing_nullable=False)
    op.alter_column('tasks', 'runtime_seconds',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_comment='运行了时长（秒）')
    op.alter_column('tasks', 'host',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True,
               existing_comment='压测目标地址，如http://127.0.0.1:8001')
    op.alter_column('cases', 'expected_response_time',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_comment='预期响应时间（ms）')
    op.alter_column('cases', 'expected_status',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False,
               existing_comment='预期响应状态码')
    # ### end Alembic commands ###
