"""Create initial tables

Revision ID: 1dc9f925c6c6
Revises: 
Create Date: 2026-02-04 10:34:40.541487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '1dc9f925c6c6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('name', sa.String(length=255), nullable=False, comment='用例名称'),
    sa.Column('type', sa.String(length=20), nullable=False, comment='用例类型'),
    sa.Column('method', sa.String(length=10), nullable=True, comment='请求方法'),
    sa.Column('url', sa.String(length=500), nullable=False, comment='请求URL'),
    sa.Column('description', sa.Text(), nullable=True, comment='用例描述'),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'ARCHIVED', 'DRAFT', name='status'), nullable=False, comment='用例状态'),
    sa.Column('project_id', sa.Integer(), nullable=False, comment='所属项目id'),
    sa.Column('project', sa.String(length=50), nullable=False, comment='所属项目名称'),
    sa.Column('headers', sa.JSON(), nullable=True, comment='请求头'),
    sa.Column('body', sa.Text(), nullable=True, comment='请求体'),
    sa.Column('expected_status', sa.String(length=10), nullable=False, comment='预期响应状态码'),
    sa.Column('expected_response_time', sa.Integer(), nullable=False, comment='预期响应时间（ms）'),
    sa.Column('assertion', sa.Text(), nullable=True, comment='断言'),
    sa.Column('pre_request_script', sa.Text(), nullable=True, comment='前置脚本'),
    sa.Column('post_request_script', sa.Text(), nullable=True, comment='后置脚本'),
    sa.Column('extract', sa.JSON(), nullable=True, comment='响应数据提取规则：{变量名: 提取路径}，默认使用jsonpath提取方式'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('created_by_name', sa.String(length=50), nullable=True, comment='创建人'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='更新人ID'),
    sa.Column('updated_by_name', sa.String(length=50), nullable=True, comment='更新人'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否已删除'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间'),
    sa.Column('deleted_by', sa.Integer(), nullable=True, comment='删除人ID'),
    sa.Column('deleted_by_name', sa.String(length=50), nullable=True, comment='删除人'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_id'), 'cases', ['id'], unique=False)
    op.create_table('project_members',
    sa.Column('project_id', sa.Integer(), nullable=False, comment='项目id'),
    sa.Column('member_id', sa.Integer(), nullable=False, comment='用户id'),
    sa.Column('member_role', sa.Enum('OWNER', 'ADMIN', 'DEVELOPER', 'TEACHER', 'VIEWER', name='memberroleenum'), nullable=False, comment='项目成员角色'),
    sa.Column('join_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='加入时间'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否有效'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('created_by_name', sa.String(length=50), nullable=True, comment='创建人'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='更新人ID'),
    sa.Column('updated_by_name', sa.String(length=50), nullable=True, comment='更新人'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否已删除'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间'),
    sa.Column('deleted_by', sa.Integer(), nullable=True, comment='删除人ID'),
    sa.Column('deleted_by_name', sa.String(length=50), nullable=True, comment='删除人'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_members_id'), 'project_members', ['id'], unique=False)
    op.create_table('projects',
    sa.Column('name', sa.String(length=100), nullable=False, comment='项目名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='项目描述'),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'ARCHIVED', name='projectstatusenum'), nullable=False, comment='项目状态'),
    sa.Column('priority', sa.Enum('HIGH', 'LOW', 'MEDIUM', name='projectpriorityenum'), nullable=False, comment='项目优先级'),
    sa.Column('tags', sa.JSON(), nullable=True, comment='项目标签'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('created_by_name', sa.String(length=50), nullable=True, comment='创建人'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='更新人ID'),
    sa.Column('updated_by_name', sa.String(length=50), nullable=True, comment='更新人'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否已删除'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间'),
    sa.Column('deleted_by', sa.Integer(), nullable=True, comment='删除人ID'),
    sa.Column('deleted_by_name', sa.String(length=50), nullable=True, comment='删除人'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_table('scenario_cases',
    sa.Column('scenario_id', sa.Integer(), nullable=False, comment='场景id'),
    sa.Column('case_id', sa.Integer(), nullable=False, comment='用例id'),
    sa.Column('order', sa.Integer(), nullable=False, comment='序号'),
    sa.Column('weight', sa.Integer(), nullable=False, comment='权重'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('created_by_name', sa.String(length=50), nullable=True, comment='创建人'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='更新人ID'),
    sa.Column('updated_by_name', sa.String(length=50), nullable=True, comment='更新人'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否已删除'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间'),
    sa.Column('deleted_by', sa.Integer(), nullable=True, comment='删除人ID'),
    sa.Column('deleted_by_name', sa.String(length=50), nullable=True, comment='删除人'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenario_cases_id'), 'scenario_cases', ['id'], unique=False)
    op.create_table('scenarios',
    sa.Column('name', sa.String(length=255), nullable=False, comment='场景名称'),
    sa.Column('project_id', sa.Integer(), nullable=False, comment='所属项目id'),
    sa.Column('project', sa.String(length=50), nullable=False, comment='所属项目名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='用例描述'),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'ARCHIVED', 'DRAFT', name='status'), nullable=False, comment='场景状态'),
    sa.Column('total_testcases', sa.Integer(), nullable=False, comment='关联用例总数'),
    sa.Column('last_run', sa.DateTime(timezone=True), nullable=True, comment='最后运行时间'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('created_by_name', sa.String(length=50), nullable=True, comment='创建人'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='更新人ID'),
    sa.Column('updated_by_name', sa.String(length=50), nullable=True, comment='更新人'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否已删除'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间'),
    sa.Column('deleted_by', sa.Integer(), nullable=True, comment='删除人ID'),
    sa.Column('deleted_by_name', sa.String(length=50), nullable=True, comment='删除人'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenarios_id'), 'scenarios', ['id'], unique=False)
    op.create_table('tasks',
    sa.Column('name', sa.String(length=100), nullable=False, comment='任务名称，如支付接口压测'),
    sa.Column('description', sa.Text(), nullable=True, comment='任务描述'),
    sa.Column('owner', sa.String(length=50), nullable=False, comment='任务负责人'),
    sa.Column('owner_id', sa.Integer(), nullable=False, comment='任务负责人id'),
    sa.Column('scenario_id', sa.Integer(), nullable=False, comment='场景id'),
    sa.Column('scenario', sa.String(length=100), nullable=False, comment='关联场景名称'),
    sa.Column('project_id', sa.Integer(), nullable=False, comment='所属项目id'),
    sa.Column('project', sa.String(length=50), nullable=False, comment='所属项目名称'),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELED', name='status'), nullable=False, comment='任务状态'),
    sa.Column('host', sa.String(length=200), nullable=True, comment='压测目标地址，如http://127.0.0.1:8001'),
    sa.Column('users', sa.Integer(), nullable=False, comment='并发用户数'),
    sa.Column('spawn_rate', sa.Integer(), nullable=False, comment='生产速率'),
    sa.Column('duration', sa.Integer(), nullable=False, comment='执行时长,seconds'),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True, comment='任务完成时间'),
    sa.Column('stats', mssql.JSON(), nullable=True, comment='统计数据'),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True, comment='压测开始时间（对应start_time）'),
    sa.Column('runtime_seconds', sa.Integer(), nullable=False, comment='运行了时长（秒）'),
    sa.Column('runtime', sa.String(length=20), nullable=True, comment='运行了时长（格式化，如00:00:04）'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('created_by_name', sa.String(length=50), nullable=True, comment='创建人'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='更新人ID'),
    sa.Column('updated_by_name', sa.String(length=50), nullable=True, comment='更新人'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否已删除'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间'),
    sa.Column('deleted_by', sa.Integer(), nullable=True, comment='删除人ID'),
    sa.Column('deleted_by_name', sa.String(length=50), nullable=True, comment='删除人'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('avatar', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True, comment='最后登录时间'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('created_by_name', sa.String(length=50), nullable=True, comment='创建人'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='更新人ID'),
    sa.Column('updated_by_name', sa.String(length=50), nullable=True, comment='更新人'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否已删除'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间'),
    sa.Column('deleted_by', sa.Integer(), nullable=True, comment='删除人ID'),
    sa.Column('deleted_by_name', sa.String(length=50), nullable=True, comment='删除人'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_scenarios_id'), table_name='scenarios')
    op.drop_table('scenarios')
    op.drop_index(op.f('ix_scenario_cases_id'), table_name='scenario_cases')
    op.drop_table('scenario_cases')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_project_members_id'), table_name='project_members')
    op.drop_table('project_members')
    op.drop_index(op.f('ix_cases_id'), table_name='cases')
    op.drop_table('cases')
    # ### end Alembic commands ###
