"""update model project_member.member_name

Revision ID: 7b1bc07dd493
Revises: 7d07623dab94
Create Date: 2026-02-05 16:44:06.688773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b1bc07dd493'
down_revision: Union[str, Sequence[str], None] = '7d07623dab94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_members', sa.Column('member_name', sa.String(length=50), nullable=False, comment='用户名称'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_members', 'member_name')
    # ### end Alembic commands ###
