"""init

Revision ID: f3d02931aba7
Revises: c4b91ed8a117
Create Date: 2026-03-17 17:53:20.953404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f3d02931aba7'
down_revision: Union[str, Sequence[str], None] = 'c4b91ed8a117'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cases', 'project_id',
               existing_type=mysql.BIGINT(),
               comment='所属项目id',
               existing_nullable=False)
    op.alter_column('cases', 'id',
               existing_type=mysql.BIGINT(),
               comment='主键ID',
               existing_nullable=False,
               autoincrement=False)
    op.alter_column('cases', 'created_by',
               existing_type=mysql.BIGINT(),
               comment='创建人ID',
               existing_nullable=True)
    op.alter_column('cases', 'updated_by',
               existing_type=mysql.BIGINT(),
               comment='更新人ID',
               existing_nullable=True)
    op.alter_column('cases', 'deleted_by',
               existing_type=mysql.BIGINT(),
               comment='删除人ID',
               existing_nullable=True)
    op.alter_column('project_members', 'project_id',
               existing_type=mysql.BIGINT(),
               comment='项目id',
               existing_nullable=False)
    op.alter_column('project_members', 'member_id',
               existing_type=mysql.BIGINT(),
               comment='用户id',
               existing_nullable=False)
    op.alter_column('project_members', 'id',
               existing_type=mysql.BIGINT(),
               comment='主键ID',
               existing_nullable=False,
               autoincrement=False)
    op.alter_column('project_members', 'created_by',
               existing_type=mysql.BIGINT(),
               comment='创建人ID',
               existing_nullable=True)
    op.alter_column('project_members', 'updated_by',
               existing_type=mysql.BIGINT(),
               comment='更新人ID',
               existing_nullable=True)
    op.alter_column('project_members', 'deleted_by',
               existing_type=mysql.BIGINT(),
               comment='删除人ID',
               existing_nullable=True)
    op.alter_column('projects', 'id',
               existing_type=mysql.BIGINT(),
               comment='主键ID',
               existing_nullable=False,
               autoincrement=False)
    op.alter_column('projects', 'created_by',
               existing_type=mysql.BIGINT(),
               comment='创建人ID',
               existing_nullable=True)
    op.alter_column('projects', 'updated_by',
               existing_type=mysql.BIGINT(),
               comment='更新人ID',
               existing_nullable=True)
    op.alter_column('projects', 'deleted_by',
               existing_type=mysql.BIGINT(),
               comment='删除人ID',
               existing_nullable=True)
    op.alter_column('scenario_cases', 'scenario_id',
               existing_type=mysql.BIGINT(),
               comment='场景id',
               existing_nullable=False)
    op.alter_column('scenario_cases', 'case_id',
               existing_type=mysql.BIGINT(),
               comment='用例id',
               existing_nullable=False)
    op.alter_column('scenario_cases', 'id',
               existing_type=mysql.BIGINT(),
               comment='主键ID',
               existing_nullable=False,
               autoincrement=False)
    op.alter_column('scenario_cases', 'created_by',
               existing_type=mysql.BIGINT(),
               comment='创建人ID',
               existing_nullable=True)
    op.alter_column('scenario_cases', 'updated_by',
               existing_type=mysql.BIGINT(),
               comment='更新人ID',
               existing_nullable=True)
    op.alter_column('scenario_cases', 'deleted_by',
               existing_type=mysql.BIGINT(),
               comment='删除人ID',
               existing_nullable=True)
    op.alter_column('scenarios', 'project_id',
               existing_type=mysql.BIGINT(),
               comment='所属项目id',
               existing_nullable=False)
    op.alter_column('scenarios', 'id',
               existing_type=mysql.BIGINT(),
               comment='主键ID',
               existing_nullable=False,
               autoincrement=False)
    op.alter_column('scenarios', 'created_by',
               existing_type=mysql.BIGINT(),
               comment='创建人ID',
               existing_nullable=True)
    op.alter_column('scenarios', 'updated_by',
               existing_type=mysql.BIGINT(),
               comment='更新人ID',
               existing_nullable=True)
    op.alter_column('scenarios', 'deleted_by',
               existing_type=mysql.BIGINT(),
               comment='删除人ID',
               existing_nullable=True)
    op.alter_column('task_scenarios', 'task_id',
               existing_type=mysql.BIGINT(),
               comment='任务id',
               existing_nullable=False)
    op.alter_column('task_scenarios', 'scenario_id',
               existing_type=mysql.BIGINT(),
               comment='场景id',
               existing_nullable=False)
    op.alter_column('task_scenarios', 'id',
               existing_type=mysql.BIGINT(),
               comment='主键ID',
               existing_nullable=False,
               autoincrement=False)
    op.alter_column('task_scenarios', 'created_by',
               existing_type=mysql.BIGINT(),
               comment='创建人ID',
               existing_nullable=True)
    op.alter_column('task_scenarios', 'updated_by',
               existing_type=mysql.BIGINT(),
               comment='更新人ID',
               existing_nullable=True)
    op.alter_column('task_scenarios', 'deleted_by',
               existing_type=mysql.BIGINT(),
               comment='删除人ID',
               existing_nullable=True)
    op.alter_column('tasks', 'owner_id',
               existing_type=mysql.BIGINT(),
               comment='任务负责人id',
               existing_nullable=False)
    op.alter_column('tasks', 'project_id',
               existing_type=mysql.BIGINT(),
               comment='所属项目id',
               existing_nullable=False)
    op.alter_column('tasks', 'id',
               existing_type=mysql.BIGINT(),
               comment='主键ID',
               existing_nullable=False,
               autoincrement=False)
    op.alter_column('tasks', 'created_by',
               existing_type=mysql.BIGINT(),
               comment='创建人ID',
               existing_nullable=True)
    op.alter_column('tasks', 'updated_by',
               existing_type=mysql.BIGINT(),
               comment='更新人ID',
               existing_nullable=True)
    op.alter_column('tasks', 'deleted_by',
               existing_type=mysql.BIGINT(),
               comment='删除人ID',
               existing_nullable=True)
    op.alter_column('users', 'id',
               existing_type=mysql.BIGINT(),
               comment='主键ID',
               existing_nullable=False,
               autoincrement=False)
    op.alter_column('users', 'created_by',
               existing_type=mysql.BIGINT(),
               comment='创建人ID',
               existing_nullable=True)
    op.alter_column('users', 'updated_by',
               existing_type=mysql.BIGINT(),
               comment='更新人ID',
               existing_nullable=True)
    op.alter_column('users', 'deleted_by',
               existing_type=mysql.BIGINT(),
               comment='删除人ID',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'deleted_by',
               existing_type=mysql.BIGINT(),
               comment=None,
               existing_comment='删除人ID',
               existing_nullable=True)
    op.alter_column('users', 'updated_by',
               existing_type=mysql.BIGINT(),
               comment=None,
               existing_comment='更新人ID',
               existing_nullable=True)
    op.alter_column('users', 'created_by',
               existing_type=mysql.BIGINT(),
               comment=None,
               existing_comment='创建人ID',
               existing_nullable=True)
    op.alter_column('users', 'id',
               existing_type=mysql.BIGINT(),
               comment=None,
               existing_comment='主键ID',
               existing_nullable=False,
               autoincrement=False)
    op.alter_column('tasks', 'deleted_by',
               existing_type=mysql.BIGINT(),
               comment=None,
               existing_comment='删除人ID',
               existing_nullable=True)
    op.alter_column('tasks', 'updated_by',
               existing_type=mysql.BIGINT(),
               comment=None,
               existing_comment='更新人ID',
               existing_nullable=True)
    op.alter_column('tasks', 'created_by',
               existing_type=mysql.BIGINT(),
               comment=None,
               existing_comment='创建人ID',
               existing_nullable=True)
    op.alter_column('tasks', 'id',
               existing_type=mysql.BIGINT(),
               comment=None,
               existing_comment='主键ID',
               existing_nullable=False,
               autoincrement=False)
    op.alter_column('tasks', 'project_id',
               existing_type=mysql.BIGINT(),
               comment=None,
               existing_comment='所属项目id',
               existing_nullable=False)
    op.alter_column('tasks', 'owner_id',
               existing_type=mysql.BIGINT(),
               comment=None,
               existing_comment='任务负责人id',
               existing_nullable=False)
    op.alter_column('task_scenarios', 'deleted_by',
               existing_type=mysql.BIGINT(),
               comment=None,
               existing_comment='删除人ID',
               existing_nullable=True)
    op.alter_column('task_scenarios', 'updated_by',
               existing_type=mysql.BIGINT(),
               comment=None,
               existing_comment='更新人ID',
               existing_nullable=True)
    op.alter_column('task_scenarios', 'created_by',
               existing_type=mysql.BIGINT(),
               comment=None,
               existing_comment='创建人ID',
               existing_nullable=True)
    op.alter_column('task_scenarios', 'id',
               existing_type=mysql.BIGINT(),
               comment=None,
               existing_comment='主键ID',
               existing_nullable=False,
               autoincrement=False)
    op.alter_column('task_scenarios', 'scenario_id',
               existing_type=mysql.BIGINT(),
               comment=None,
               existing_comment='场景id',
               existing_nullable=False)
    op.alter_column('task_scenarios', 'task_id',
               existing_type=mysql.BIGINT(),
               comment=None,
               existing_comment='任务id',
               existing_nullable=False)
    op.alter_column('scenarios', 'deleted_by',
               existing_type=mysql.BIGINT(),
               comment=None,
               existing_comment='删除人ID',
               existing_nullable=True)
    op.alter_column('scenarios', 'updated_by',
               existing_type=mysql.BIGINT(),
               comment=None,
               existing_comment='更新人ID',
               existing_nullable=True)
    op.alter_column('scenarios', 'created_by',
               existing_type=mysql.BIGINT(),
               comment=None,
               existing_comment='创建人ID',
               existing_nullable=True)
    op.alter_column('scenarios', 'id',
               existing_type=mysql.BIGINT(),
               comment=None,
               existing_comment='主键ID',
               existing_nullable=False,
               autoincrement=False)
    op.alter_column('scenarios', 'project_id',
               existing_type=mysql.BIGINT(),
               comment=None,
               existing_comment='所属项目id',
               existing_nullable=False)
    op.alter_column('scenario_cases', 'deleted_by',
               existing_type=mysql.BIGINT(),
               comment=None,
               existing_comment='删除人ID',
               existing_nullable=True)
    op.alter_column('scenario_cases', 'updated_by',
               existing_type=mysql.BIGINT(),
               comment=None,
               existing_comment='更新人ID',
               existing_nullable=True)
    op.alter_column('scenario_cases', 'created_by',
               existing_type=mysql.BIGINT(),
               comment=None,
               existing_comment='创建人ID',
               existing_nullable=True)
    op.alter_column('scenario_cases', 'id',
               existing_type=mysql.BIGINT(),
               comment=None,
               existing_comment='主键ID',
               existing_nullable=False,
               autoincrement=False)
    op.alter_column('scenario_cases', 'case_id',
               existing_type=mysql.BIGINT(),
               comment=None,
               existing_comment='用例id',
               existing_nullable=False)
    op.alter_column('scenario_cases', 'scenario_id',
               existing_type=mysql.BIGINT(),
               comment=None,
               existing_comment='场景id',
               existing_nullable=False)
    op.alter_column('projects', 'deleted_by',
               existing_type=mysql.BIGINT(),
               comment=None,
               existing_comment='删除人ID',
               existing_nullable=True)
    op.alter_column('projects', 'updated_by',
               existing_type=mysql.BIGINT(),
               comment=None,
               existing_comment='更新人ID',
               existing_nullable=True)
    op.alter_column('projects', 'created_by',
               existing_type=mysql.BIGINT(),
               comment=None,
               existing_comment='创建人ID',
               existing_nullable=True)
    op.alter_column('projects', 'id',
               existing_type=mysql.BIGINT(),
               comment=None,
               existing_comment='主键ID',
               existing_nullable=False,
               autoincrement=False)
    op.alter_column('project_members', 'deleted_by',
               existing_type=mysql.BIGINT(),
               comment=None,
               existing_comment='删除人ID',
               existing_nullable=True)
    op.alter_column('project_members', 'updated_by',
               existing_type=mysql.BIGINT(),
               comment=None,
               existing_comment='更新人ID',
               existing_nullable=True)
    op.alter_column('project_members', 'created_by',
               existing_type=mysql.BIGINT(),
               comment=None,
               existing_comment='创建人ID',
               existing_nullable=True)
    op.alter_column('project_members', 'id',
               existing_type=mysql.BIGINT(),
               comment=None,
               existing_comment='主键ID',
               existing_nullable=False,
               autoincrement=False)
    op.alter_column('project_members', 'member_id',
               existing_type=mysql.BIGINT(),
               comment=None,
               existing_comment='用户id',
               existing_nullable=False)
    op.alter_column('project_members', 'project_id',
               existing_type=mysql.BIGINT(),
               comment=None,
               existing_comment='项目id',
               existing_nullable=False)
    op.alter_column('cases', 'deleted_by',
               existing_type=mysql.BIGINT(),
               comment=None,
               existing_comment='删除人ID',
               existing_nullable=True)
    op.alter_column('cases', 'updated_by',
               existing_type=mysql.BIGINT(),
               comment=None,
               existing_comment='更新人ID',
               existing_nullable=True)
    op.alter_column('cases', 'created_by',
               existing_type=mysql.BIGINT(),
               comment=None,
               existing_comment='创建人ID',
               existing_nullable=True)
    op.alter_column('cases', 'id',
               existing_type=mysql.BIGINT(),
               comment=None,
               existing_comment='主键ID',
               existing_nullable=False,
               autoincrement=False)
    op.alter_column('cases', 'project_id',
               existing_type=mysql.BIGINT(),
               comment=None,
               existing_comment='所属项目id',
               existing_nullable=False)
    # ### end Alembic commands ###
