"""add task scenarios

Revision ID: 6941380e7b68
Revises: 7b1bc07dd493
Create Date: 2026-03-16 17:45:12.817661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6941380e7b68'
down_revision: Union[str, Sequence[str], None] = '7b1bc07dd493'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_scenarios',
    sa.Column('task_id', sa.Integer(), nullable=False, comment='任务id'),
    sa.Column('scenario_id', sa.Integer(), nullable=False, comment='场景id'),
    sa.Column('scenario', sa.String(length=100), nullable=False, comment='关联场景名称'),
    sa.Column('order', sa.Integer(), nullable=False, comment='执行顺序'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('created_by_name', sa.String(length=50), nullable=True, comment='创建人'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='更新人ID'),
    sa.Column('updated_by_name', sa.String(length=50), nullable=True, comment='更新人'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否已删除'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间'),
    sa.Column('deleted_by', sa.Integer(), nullable=True, comment='删除人ID'),
    sa.Column('deleted_by_name', sa.String(length=50), nullable=True, comment='删除人'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_scenarios_id'), 'task_scenarios', ['id'], unique=False)
    op.drop_column('tasks', 'scenario')
    op.drop_column('tasks', 'scenario_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('scenario_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='场景id'))
    op.add_column('tasks', sa.Column('scenario', mysql.VARCHAR(length=100), nullable=False, comment='关联场景名称'))
    op.drop_index(op.f('ix_task_scenarios_id'), table_name='task_scenarios')
    op.drop_table('task_scenarios')
    # ### end Alembic commands ###
